pipeline{
    agent any

    stages{
        stage('Checkout') {
            checkout([$class: 'GitSCM', branches: [[name: '*/main']], userRemoteConfigs: [[url: 'https://github.com/thunderxx2/greenmarket.git']]])
        }
    }

    stage('Build') {
        steps {
            sh './gradlew clean assembleDebug'
        }
    }

    stage('Test'){
        steps{
            sh './gradlew test'
        }
    }

    stage('Publish APK'){
        steps{
            archiveArtifacts artifacts: 'app/build/outputs/apk/debug/*.apk', fingerprint: true
        }
    }

    stage('Deploy'){
        steps {
            //
        }
    }

    post {
        cleanWs()
    }
}