pipeline{
    agent any

    environment {
            ANDROID_HOME = '/Users/dushyantpawar/Library/Android/sdk'
        }

    stages{

        stage('Print Environment Variable') {
            steps {
                echo "ANDROID_HOME: ${env.ANDROID_HOME}"
            }
        }

        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], userRemoteConfigs: [[url: 'https://github.com/thunderxx2/greenmarket.git']]])
            }
        }

    stage('Build') {
        steps {
            sh './gradlew clean assembleDebug'
        }
    }

    stage('Test'){
        steps{
            sh './gradlew test'
        }
    }

    stage('Publish APK'){
        steps{
            archiveArtifacts artifacts: 'app/build/outputs/apk/debug/*.apk', fingerprint: true
        }
    }

//     stage('Deploy'){
//         steps {
//             //
//         }
//     }
  }

      post {
        always {
          cleanWs()
          }
      }
}